name: Puppeteer-dart analyze and test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [linux-latest, macos-latest, windows-latest]
        dart: ['2.7.0', '2.8.0-dev.3.0']
    runs-on: ${{ matrix.os }}
#    env:
#      #In travis/docker we need the --no-sandbox flag in chrome
#      CHROME_FORCE_NO_SANDBOX: true
    steps:
      - uses: actions/checkout@v2
      #- run: .github/scripts/install_dart.sh
      #  env:
      #    DART_SDK_VERSION: ${{ matrix.dart }}
      #  shell: bash
      - uses: xvrh/setup-dart@v1
        with:
          dart-version: '2.7.0'
      - run: dart --version
      - run: pub get
#      - run: dart example/download_chromium.dart
#      - run: pub run test -P ci --platform vm
      - name: "check for uncommitted changes"
        # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
        run: |
          git diff --exit-code --stat -- . \
          || (echo "##[error] found changed files after build. please run 'dart tool/prepare_submit.dart'" \
                   "and check in all changes" \
              && exit 1)