name: Puppeteer-dart analyze and test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [linux-latest, macos-latest, windows-latest]
        dart: ['2.7.0', '2.8.0-dev.3.0']
    runs-on: ${{ matrix.os }}
#    env:
#      #In travis/docker we need the --no-sandbox flag in chrome
#      CHROME_FORCE_NO_SANDBOX: true
    steps:
      - uses: actions/checkout@v2
      - run: .github/scripts/install_dart.sh
        env:
          DART_SDK_VERSION: ${{ matrix.dart }}
        shell: bash
      - run: dart --version
        shell: bash
      - run: pub get
        shell: bash
#      - run: dart example/download_chromium.dart
#      - run: pub run test -P ci --platform vm
